### ISSUE TITLE
Hidden cards take up card slots

### ISSUE THREAD

**Issue by ttaidapos** [Savjee/button-text-card#18] opened 2020-04-28 02:33 UTC
I'm using three of these cards in position 1,2,3.  When hidden, sometimes they take up the space and other times not.  See below.  resizing the window fixes the problem even if you resize it to the original size.  The issue is consistent and so is the fix.

**Here they take up all three spots and hence a whole column**
![image](https://user-images.githubusercontent.com/27898709/80440496-7f622380-88ce-11ea-97f6-55b98aaed672.png)

**Same window size just clicked on edit**
![image](https://user-images.githubusercontent.com/27898709/80440539-97d23e00-88ce-11ea-939d-6521deb74feb.png)

**Comment by Savjee** [comment] 2020-05-03 15:54
What browser are you using? I'm personally testing in Chrome and Safari and haven't seen this issue yet.

**Comment by ttaidapos** [comment] 2020-05-04 02:23
> What browser are you using? I'm personally testing in Chrome and Safari and haven't seen this issue yet.

I'm on Chrome Version 81.0.4044.129 (Official Build) (64-bit).  F5, CTRL+F5 doesn't fix it, only resizing the window.  Tried in Chrome incognito and same results.

**Comment by ttaidapos** [comment] 2020-05-05 17:15
Here's another visual to help.

![image](https://user-images.githubusercontent.com/27898709/81095055-0f552e00-8eca-11ea-996b-e4868b1b56f4.png)
![image](https://user-images.githubusercontent.com/27898709/81095081-1b40f000-8eca-11ea-81b3-8c4a7dc12e09.png)

**Comment by Savjee** [comment] 2020-05-08 12:23
Can you tell me which version of Home Assistant you're running? And maybe also which front-end plugins you're using.

I can't replicate this issue, so I'm a bit puzzled.

**Comment by ttaidapos** [comment] 2020-05-08 16:21
> Can you tell me which version of Home Assistant you're running? And maybe also which front-end plugins you're using.
> 
> I can't replicate this issue, so I'm a bit puzzled.

Sure!  Should have included this info initially.  I've tested this since 107.x and it's still there even with the recent 109.x.  Also found another UI glitch that might be related, there's a bit of a gap between the two cards i added and of course you can see the gap on slot 1 as initially reported.

**Typical Card**
```
background_color: '#A81419'
entity: sensor.front_door_keypad_battery
font_color: '#fff'
hide_condition: |
  [[[ return entity.state > "6" ]]]
icon: 'mdi:comment-alert'
large: true
subtitle: 'August Key Pad battery is at 5%, replace with 2x AAA batteries.'
title: Battery Low!
type: 'custom:button-text-card'
```

![image](https://user-images.githubusercontent.com/27898709/81425806-e2995480-911d-11ea-9049-3d964d26ab72.png)
![image](https://user-images.githubusercontent.com/27898709/81425894-fd6bc900-911d-11ea-9a3f-27654f40a38c.png)
![image](https://user-images.githubusercontent.com/27898709/81425931-170d1080-911e-11ea-9896-ebbfc3c2f64a.png)

**Comment by Savjee** [comment] 2020-05-09 15:57
Quite a lot of plugins there! Could you temporarily disable all of them, except Button Text Card?

Don't forget to clear your cache before reloading.

I want to see if another plugin is causing it. If this helps, try enabling plugins one at a time to see which one is causing issues. Then I can look into possible conflicts.

**Comment by ttaidapos** [comment] 2020-05-11 02:58
> Quite a lot of plugins there! Could you temporarily disable all of them, except Button Text Card?
> 
> Don't forget to clear your cache before reloading.
> 
> I want to see if another plugin is causing it. If this helps, try enabling plugins one at a time to see which one is causing issues. Then I can look into possible conflicts.

No dice!  This is what I tried...

Removed all plugins
Restarted hass
Reinstalled button-text-card
Tried both CTRL+F5 and Chrome Incognito

My only thought is that i'm on a 4k resolution monitor?  Tried on MS Edge and no luck there either.

**Comment by ttaidapos** [comment] 2020-05-11 16:37
Here's a short video showing the issue.

https://drive.google.com/file/d/1ogoo2XCz1IHjL8BngaQXAJc6_fBYgGOp/view?usp=sharing

**Comment by ttaidapos** [comment] 2020-06-24 01:36
Any update on this one?

**Comment by Savjee** [comment] 2020-06-26 04:51
Unfortunately not. I can't replicate this issue myself so tricky to debug.

**Comment by ttaidapos** [comment] 2020-06-27 13:03
Anyone else having this issue?

**Comment by tobydriver** [comment] 2020-11-29 17:59
Hi ! 
I'm experiencing exactly the same issue as @ttaidapos.
I'm on Chrome v.87. Same issue on iOS Home Assistant app.

@ttaidapos did you find a way to fix this issue?

**Comment by ttaidapos** [comment] 2020-11-29 20:42
> Hi !
> I'm experiencing exactly the same issue as @ttaidapos.
> I'm on Chrome v.87. Same issue on iOS Home Assistant app.
> 
> @ttaidapos did you find a way to fix this issue?

Nope, just don't use it.

**Comment by Savjee** [comment] 2020-11-30 06:57
@tobydriver Could you also list all the frontend plugins you're using?
I'm guessing one of them is causing issues. Maybe you have one in common with @ttaidapos

**Comment by Savjee** [comment] 2022-02-17 17:16
I still can't reproduce this bug, and it hasn't been active in a while. Closing for now. Please reopen if needed.

**Closed as completed by Savjee** 2022-02-17 17:16 UTC
